"""fix2

Revision ID: b35dd4cb82d8
Revises: e2ede90046b0
Create Date: 2022-09-09 11:55:20.563199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35dd4cb82d8'
down_revision = 'e2ede90046b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_registered', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('blog_registered', sa.Column('created_by_chat', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_registered', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'blog_registered', 'chat', ['created_by_chat'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_registered', type_='foreignkey')
    op.drop_constraint(None, 'blog_registered', type_='foreignkey')
    op.drop_column('blog_registered', 'created_by_chat')
    op.drop_column('blog_registered', 'chat_id')
    # ### end Alembic commands ###
