"""init PublishHistory table

Revision ID: a4ab8a2a7feb
Revises: ed3d77797231
Create Date: 2022-08-27 21:23:12.722709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ab8a2a7feb'
down_revision = 'ed3d77797231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_history')
    # ### end Alembic commands ###
