"""BlogRegistered and Chat

Revision ID: c63b0c65eb9f
Revises: a526002cf4fb
Create Date: 2022-09-08 17:48:13.385456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63b0c65eb9f'
down_revision = 'a526002cf4fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_registered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_oid', sa.Integer(), nullable=True),
    sa.Column('created_by_oid', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('blog_registered')
    # ### end Alembic commands ###
