"""fix

Revision ID: e2ede90046b0
Revises: c63b0c65eb9f
Create Date: 2022-09-09 11:34:11.127391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ede90046b0'
down_revision = 'c63b0c65eb9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
